#!/bin/bash 

ARGS="$*"
ERL=`which erl`
SHELL=-noshell

if [ $# == 0 ]; then
   ARGS=""
else
   ARGS=`echo ${ARGS} | sed s/-/\?/g`

   if [ $1 == '-s' ]; then
       SHELL=
   fi
fi

$ERL -pa ebin +K true $SHELL -s distmap start ${ARGS}
